name: Container Image CI
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - uses: anchore/scan-action@v2
      with:
        path: "."
    
