on: [workflow_dispatch] 
 
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    
     
    - run: echo hello world > math-homework.txt
    - name: test
      run : |
       echo "::set-output name=action_fruit::${{github.workspace}}/math-homework.txt" 
       docker images
       docker pull bridgecrew/checkov
       docker run -t -v ${{github.workspace}}:/tf  bridgecrew/checkov -d /tf -o json      

      id: run_test
    - name: get test
      run: echo ${{(steps.run_test.outputs.action_fruit)}}
    
    
       
