on: [workflow_dispatch] 
 
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    
     
    - run: echo hello world > math-homework.txt
    - name: test
      run : |
       
       docker images
       docker pull bridgecrew/checkov
       docker run -t -v ${{github.workspace}}:/tf  bridgecrew/checkov -d /tf -o json      

   
    
    
       
