name: Example workflow for Snyk Infrastructure as Code
on: workflow_dispatch
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Run Snyk to check Kubernetes manifest file for issues
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        
